version: "3.8"

services:
  gem_server:
    image: spoonest/geminabox
    volumes:
      - "/var/www/gem_server/shared/data:/webapps/geminabox/data"
    ports:
      - 9292:9292
    networks:
      - my-net

networks:
  my-net:
    external: true
